#
version: '2'

services:
  blockchain-exos:
    image: gopherdata/gophernotes
    ports:
      - "8888:8888"
    volumes:
      - ./css/.jupyter:/root/.jupyter/
      - ./exercices_concepts:/exercices_concepts
      - ./exercices_ethereum:/exercices_ethereum
      - ./utils/:/go/utils

