version: '2'
services:
    ganachecli:
        container_name: ganache-cli
        image: trufflesuite/ganache-cli:latest
        command: bash "ganache-cli -h 0.0.0.0"
        ports:
        - 8545:8545
    truffleapp:
        container_name: truffle-app
        build:
            context: ./truffle-apps
        command: bash
        stdin_open: true
        tty: true
        ports:
        - 8080:8080
        volumes:
        - ./source/:/source
