Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/sfeir.lu/msp
    - &Org1
        Name: ShopMSP
        ID: ShopMSP
        MSPDir: crypto-config/peerOrganizations/shop.sfeir.lu/msp
        AnchorPeers:
            - Host: peer0.shop.sfeir.lu
              Port: 7051
    - &Org2
        Name: WarehouseMSP
        ID: WarehouseMSP
        MSPDir: crypto-config/peerOrganizations/warehouse.sfeir.lu/msp
        AnchorPeers:
            - Host: peer0.warehouse.sfeir.lu
              Port: 7051
Application: &ApplicationDefaults
    Organizations:
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.sfeir.lu:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
Profiles:
    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
    TwoOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2

