OrdererOrgs:
  - Name: Orderer
    Domain: sfeir.lu
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Shop
    Domain: shop.sfeir.lu
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Warehouse
    Domain: warehouse.sfeir.lu
    Template:
      Count: 1
    Users:
      Count: 1
