#
version: '2'

networks:
  sfeirntw:

services:
  ca.shop.sfeir.lu:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.shop.sfeir.lu
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.shop.sfeir.lu-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.shop.sfeir.lu-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/shop.sfeir.lu/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.shop.sfeir.lu
    networks:
      - sfeirntw

  ca.warehouse.sfeir.lu:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.warehouse.sfeir.lu
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.warehouse.sfeir.lu-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.warehouse.sfeir.lu-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/warehouse.sfeir.lu/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.warehouse.sfeir.lu
    networks:
      - sfeirntw

  orderer.sfeir.lu:
    container_name: orderer.sfeir.lu
    image: hyperledger/fabric-orderer:1.2.1
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/sfeir.lu/orderers/orderer.sfeir.lu/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/shop.sfeir.lu/peers/peer0.shop.sfeir.lu/:/etc/hyperledger/msp/peershop
        - ./crypto-config/peerOrganizations/warehouse.sfeir.lu/peers/peer0.warehouse.sfeir.lu/:/etc/hyperledger/msp/peerwarehouse
    networks:
      - sfeirntw

  peer0.shop.sfeir.lu:
    container_name: peer0.shop.sfeir.lu
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.shop.sfeir.lu
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=ShopMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.shop.sfeir.lu:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_sfeirntw
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=shop.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shop.sfeir.lu:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/shop.sfeir.lu/peers/peer0.shop.sfeir.lu/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/shop.sfeir.lu/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./sfeircc/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
    depends_on:
      - orderer.sfeir.lu
      - shop.couchdb
    networks:
      - sfeirntw

  peer0.warehouse.sfeir.lu:
    container_name: peer0.warehouse.sfeir.lu
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.warehouse.sfeir.lu
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=WarehouseMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.warehouse.sfeir.lu:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_sfeirntw
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=warehouse.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.warehouse.sfeir.lu:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/warehouse.sfeir.lu/peers/peer0.warehouse.sfeir.lu/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/warehouse.sfeir.lu/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./sfeircc/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
    depends_on:
      - peer0.shop.sfeir.lu
      - warehouse.couchdb
    networks:
      - sfeirntw


  shop.couchdb:
    container_name: shop.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - sfeirntw

  warehouse.couchdb:
    container_name: warehouse.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - sfeirntw

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=debug
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.shop.sfeir.lu:7051
      - CORE_PEER_LOCALMSPID=ShopMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/shop.sfeir.lu/users/Admin@shop.sfeir.lu/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./sfeircc/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - sfeirntw

