Organizations:
    - &OrdererOrg
        Name: !!!<CHANGE ME>!!!
        ID: !!!<CHANGE ME>!!!
        MSPDir: crypto-config/ordererOrganizations/!!!<CHANGE ME>!!!/msp
    - &Org1
        Name: !!!<CHANGE ME>!!!
        ID: !!!<CHANGE ME>!!!
        MSPDir: crypto-config/peerOrganizations/!!!<CHANGE ME>!!!/msp
        AnchorPeers:
            - Host: !!!<CHANGE ME>!!!
              Port: 7051
    - &Org2
        Name: !!!<CHANGE ME>!!!
        ID: !!!<CHANGE ME>!!!
        MSPDir: crypto-config/peerOrganizations/!!!<CHANGE ME>!!!/msp
        AnchorPeers:
            - Host: !!!<CHANGE ME>!!!
              Port: 7051
Application: &ApplicationDefaults
    Organizations:
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - !!!<CHANGE ME>!!!:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
Profiles:
    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
    TwoOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2

